### PR TITLE
update ocp instructions

### PR DESCRIPTION
**Pull request by pwright**

### CODE REVIEW

**Comment by pwright** [comment]
@carlesarnal some updates

**Comment by jsenko** [comment]
Since we're focusing on OCP, we could use OCP templates feature, which allows for providing variables to a template before it's applied. This could be useful when user has to provide the cluster router base name, like mentioned here:

```
Create a new ApicurioRegistry3 CR and routes, you'll need to change the host values in the CR (`mycluster.example.com`) to match those of your cluster
```

This is an example from 2.6, the usage is at the top and the parameters at the bottom https://github.com/Apicurio/apicurio-registry-operator/blob/main/docs/modules/ROOT/examples/templates/registry-simple-postgresql.yaml

**Comment by jsenko** [comment]
The template I linked also deploys ephemeral PostgreSQL which could be included.

**Comment by pwright** [comment]
@jsenko  I think that's a good idea,  and we should follow up.. but I suggest leaving it for later

**Comment by carlesarnal** [comment]
> @jsenko I think that's a good idea, and we should follow up.. but I suggest leaving it for later

Agreed, I think it's a good idea, but I would like to leave it for later. We can open a GH issue for that.

**Pull request merged**
